create table active_sessions (
    id bigint generated by default as identity,
    token_id varchar(64) not null unique,
    subject_email TEXT not null,
    last_active_at timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null,
    primary key (id)
);
