create table task_responses (
    id bigint generated by default as identity,
    task_id bigint not null,
    store_id bigint not null,
    employee_user_id bigint not null,
    response_date date not null,
    response_type varchar(20) not null,
    value_boolean boolean,
    value_numeric double precision,
    value_text TEXT,
    active boolean not null default true,
    created_at timestamp(6) with time zone not null,
    undone_at timestamp(6) with time zone,
    primary key (id)
);
alter table task_responses add constraint fk_task_responses_task foreign key (task_id) references tasks on delete cascade;
alter table task_responses add constraint fk_task_responses_store foreign key (store_id) references stores;
alter table task_responses add constraint fk_task_responses_employee foreign key (employee_user_id) references users;

-- Looking up (and enforcing SINGLE-completion uniqueness among) the active responses
-- for a given task/store/day is the hot path -- both the checklist read and the
-- submit/undo writes key off this triple.
create index idx_task_responses_lookup on task_responses (task_id, store_id, response_date);
create index idx_task_responses_employee on task_responses (employee_user_id);
