create table roles (id bigint generated by default as identity, description TEXT, name TEXT not null unique, primary key (id));
create table stores (active boolean not null, id bigint generated by default as identity, name TEXT not null, primary key (id));
create table user_roles (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id));
create table users (active boolean not null, created_at timestamp(6) with time zone not null, id bigint generated by default as identity, email TEXT not null unique, full_name TEXT not null, password_hash TEXT not null, primary key (id));
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
