create table raised_issues (
    id bigint generated by default as identity,
    store_id bigint not null,
    employee_user_id bigint not null,
    note TEXT not null,
    status varchar(20) not null default 'OPEN',
    raised_date date not null,
    response_text TEXT,
    responded_by_user_id bigint,
    responded_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    primary key (id)
);
alter table raised_issues add constraint fk_raised_issues_store foreign key (store_id) references stores;
alter table raised_issues add constraint fk_raised_issues_employee foreign key (employee_user_id) references users;
alter table raised_issues add constraint fk_raised_issues_responded_by foreign key (responded_by_user_id) references users;

create index idx_raised_issues_store_employee_date on raised_issues (store_id, employee_user_id, raised_date);

create table notifications (
    id bigint generated by default as identity,
    recipient_user_id bigint not null,
    title varchar(200) not null,
    message TEXT not null,
    category varchar(30) not null,
    priority varchar(20) not null default 'NORMAL',
    read boolean not null default false,
    related_issue_id bigint,
    created_at timestamp(6) with time zone not null,
    primary key (id)
);
alter table notifications add constraint fk_notifications_recipient foreign key (recipient_user_id) references users;
alter table notifications add constraint fk_notifications_related_issue foreign key (related_issue_id) references raised_issues on delete cascade;

create index idx_notifications_recipient on notifications (recipient_user_id);
