-- Raised issues: employee-reported problems during a shift, visible to the store owner.
CREATE TABLE raised_issues (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id                BIGINT        NOT NULL REFERENCES stores(id),
    employee_user_id        BIGINT        NOT NULL REFERENCES users(id),
    note                    TEXT          NOT NULL,
    status                  VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
    raised_date             DATE          NOT NULL,
    response_text           TEXT,
    responded_by_user_id    BIGINT        REFERENCES users(id),
    responded_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ   NOT NULL
);

CREATE INDEX idx_raised_issues_store_employee_date ON raised_issues(store_id, employee_user_id, raised_date);

ALTER TABLE raised_issues
    ADD CONSTRAINT fk_raised_issues_store    FOREIGN KEY (store_id)             REFERENCES stores(id),
    ADD CONSTRAINT fk_raised_issues_employee FOREIGN KEY (employee_user_id)     REFERENCES users(id),
    ADD CONSTRAINT fk_raised_issues_responded_by FOREIGN KEY (responded_by_user_id) REFERENCES users(id);

-- Notifications: in-app alerts delivered to a specific user.
CREATE TABLE notifications (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id   BIGINT        NOT NULL REFERENCES users(id),
    title               VARCHAR(200)  NOT NULL,
    message             TEXT          NOT NULL,
    category            VARCHAR(30)   NOT NULL,
    priority            VARCHAR(20)   NOT NULL DEFAULT 'NORMAL',
    read                BOOLEAN       NOT NULL DEFAULT FALSE,
    related_issue_id    BIGINT        REFERENCES raised_issues(id) ON DELETE CASCADE,
    created_at          TIMESTAMPTZ   NOT NULL
);

CREATE INDEX idx_notifications_recipient ON notifications(recipient_user_id);

ALTER TABLE notifications
    ADD CONSTRAINT fk_notifications_recipient     FOREIGN KEY (recipient_user_id) REFERENCES users(id),
    ADD CONSTRAINT fk_notifications_related_issue FOREIGN KEY (related_issue_id)  REFERENCES raised_issues(id) ON DELETE CASCADE;
