create table super_admins (
    super_admin_id bigint generated by default as identity,
    name TEXT not null,
    email TEXT not null unique,
    password_hash TEXT not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    primary key (super_admin_id)
);

alter table stores add column location TEXT;

create table store_owners (
    id bigint generated by default as identity,
    store_id bigint not null unique,
    owner_id bigint not null unique,
    created_at timestamp(6) with time zone not null,
    primary key (id)
);
alter table store_owners add constraint fk_store_owners_store foreign key (store_id) references stores;
alter table store_owners add constraint fk_store_owners_owner foreign key (owner_id) references users;

create table store_employees (
    id bigint generated by default as identity,
    store_id bigint not null,
    employee_id bigint not null unique,
    created_at timestamp(6) with time zone not null,
    primary key (id)
);
alter table store_employees add constraint fk_store_employees_store foreign key (store_id) references stores;
alter table store_employees add constraint fk_store_employees_employee foreign key (employee_id) references users;
