-- Global supplier directory (Phase 2) -- managed by Super Admin, shared
-- platform-wide (e.g. Walmart, Sam's Club).
CREATE TABLE suppliers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT          NOT NULL,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL,
    updated_at      TIMESTAMPTZ   NOT NULL
);
