-- Global inventory categories (Phase 2) -- managed by Super Admin, shared
-- platform-wide. Distinct from `categories`, which is per-owner and scoped
-- to Phase 1 task categories.
CREATE TABLE inventory_categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT          NOT NULL,
    display_order   INTEGER       NOT NULL DEFAULT 0,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL,
    updated_at      TIMESTAMPTZ   NOT NULL
);
