-- Global inventory item master catalog (Phase 2) -- managed by Super Admin.
-- Assigned to individual stores via store_inventory_items (V45).
CREATE TABLE inventory_items (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id             BIGINT        NOT NULL,
    name                    TEXT          NOT NULL,
    unit_of_measurement     TEXT          NOT NULL,
    active                  BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ   NOT NULL,
    updated_at              TIMESTAMPTZ   NOT NULL
);

CREATE INDEX idx_inventory_items_category ON inventory_items(category_id);

ALTER TABLE inventory_items
    ADD CONSTRAINT fk_inventory_items_category FOREIGN KEY (category_id) REFERENCES inventory_categories(id);
