-- Assignment of a global inventory item to a specific store (Phase 2). Super
-- Admin creates the row (assigns the item to the store); Owner/Admin only
-- ever updates min_weekday/min_weekend/preferred_supplier_id on it -- they
-- never create or delete the assignment itself.
CREATE TABLE store_inventory_items (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id                BIGINT        NOT NULL,
    inventory_item_id       BIGINT        NOT NULL,
    min_weekday             INTEGER,
    min_weekend             INTEGER,
    preferred_supplier_id   BIGINT,
    active                  BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ   NOT NULL,
    updated_at              TIMESTAMPTZ   NOT NULL
);

CREATE UNIQUE INDEX uq_store_inventory_items_store_item ON store_inventory_items(store_id, inventory_item_id);
CREATE INDEX idx_store_inventory_items_store ON store_inventory_items(store_id);

ALTER TABLE store_inventory_items
    ADD CONSTRAINT fk_store_inventory_items_store             FOREIGN KEY (store_id)              REFERENCES stores(id),
    ADD CONSTRAINT fk_store_inventory_items_inventory_item    FOREIGN KEY (inventory_item_id)     REFERENCES inventory_items(id),
    ADD CONSTRAINT fk_store_inventory_items_supplier          FOREIGN KEY (preferred_supplier_id) REFERENCES suppliers(id);
