-- Employee daily physical stock counts (Phase 2). quantity_needed is
-- computed AND persisted at submit time (max(0, minTarget - currentCount))
-- so historical records stay accurate even if the item's min thresholds
-- change later. One canonical count per store-item per day; Owner/Admin can
-- correct a past row afterward (does not create a new one).
CREATE TABLE stock_checks (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_inventory_item_id     BIGINT        NOT NULL,
    checked_by_user_id          BIGINT        NOT NULL,
    check_date                  DATE          NOT NULL,
    current_count               INTEGER       NOT NULL,
    quantity_needed             INTEGER       NOT NULL,
    created_at                  TIMESTAMPTZ   NOT NULL
);

CREATE UNIQUE INDEX uq_stock_checks_item_date ON stock_checks(store_inventory_item_id, check_date);

ALTER TABLE stock_checks
    ADD CONSTRAINT fk_stock_checks_store_inventory_item FOREIGN KEY (store_inventory_item_id) REFERENCES store_inventory_items(id),
    ADD CONSTRAINT fk_stock_checks_checked_by           FOREIGN KEY (checked_by_user_id)       REFERENCES users(id);
