-- Store order list (Phase 2). References inventory_item directly (not
-- store_inventory_item) so an order survives even if Super Admin later
-- deactivates the item's store assignment while it's still ORDERED.
-- Outstanding entries never disappear on their own -- they remain until
-- their status is updated to RECEIVED.
CREATE TABLE order_list_entries (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id            BIGINT        NOT NULL,
    inventory_item_id   BIGINT        NOT NULL,
    quantity_needed     INTEGER       NOT NULL,
    supplier_id         BIGINT,
    note                TEXT,
    status              VARCHAR(20)   NOT NULL DEFAULT 'NEEDS_ORDERING',
    ad_hoc              BOOLEAN       NOT NULL DEFAULT FALSE,
    raised_by_user_id   BIGINT,
    created_at          TIMESTAMPTZ   NOT NULL,
    updated_at          TIMESTAMPTZ   NOT NULL
);

-- At most one active (non-RECEIVED) entry per store+item -- mirrors V19's
-- partial-unique-index mechanism for closing the check-then-act race between
-- a stock-check-triggered shortage and an independent ad-hoc report landing
-- for the same item concurrently.
CREATE UNIQUE INDEX idx_order_list_entries_active ON order_list_entries(store_id, inventory_item_id) WHERE status <> 'RECEIVED';
CREATE INDEX idx_order_list_entries_store_status ON order_list_entries(store_id, status);

ALTER TABLE order_list_entries
    ADD CONSTRAINT fk_order_list_entries_store         FOREIGN KEY (store_id)          REFERENCES stores(id),
    ADD CONSTRAINT fk_order_list_entries_item          FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id),
    ADD CONSTRAINT fk_order_list_entries_supplier      FOREIGN KEY (supplier_id)       REFERENCES suppliers(id),
    ADD CONSTRAINT fk_order_list_entries_raised_by     FOREIGN KEY (raised_by_user_id) REFERENCES users(id);
