create table categories (
    id bigint generated by default as identity,
    store_id bigint not null,
    name TEXT not null,
    display_order integer not null default 0,
    active boolean not null default true,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    primary key (id)
);
alter table categories add constraint fk_categories_store foreign key (store_id) references stores;
alter table categories add constraint uq_categories_store_name unique (store_id, name);
