-- Recent Activity feed (Super Admin: platform-wide; Owner Admin: their own
-- store(s)). actor_name/store_name are denormalized text, not just FKs, so a
-- log entry stays readable even after the actor or store is later renamed,
-- deactivated, or deleted -- same reasoning as admin_corrections.corrected_by_name.
create table activity_log (
    id bigint generated by default as identity primary key,
    action_type varchar(50) not null,
    actor_name varchar(150) not null,
    actor_role varchar(20) not null,
    store_id bigint references stores on delete set null,
    store_name varchar(150),
    entity_type varchar(50),
    entity_name varchar(200),
    description varchar(300) not null,
    occurred_at timestamptz not null default now()
);

create index idx_activity_log_store_id on activity_log (store_id);
create index idx_activity_log_occurred_at on activity_log (occurred_at desc);
