-- "Missed Tasks" makeup links: lets an employee defer completing a past missed
-- task instance until today's occurrence of the same task is completed, at
-- which point the linked past instance is auto-completed too (see
-- TaskMakeupLinkService.fulfillPendingLinksIfCompleted).
--
-- Invariant enforced application-side (TaskMakeupLinkService): a missed
-- instance (task_id, store_id, past_date) has either an active task_responses
-- row or at most one PENDING link, never both.
create table task_makeup_links (
    id bigint generated by default as identity primary key,
    task_id bigint not null references tasks on delete cascade,
    store_id bigint not null references stores,
    past_date date not null,
    linked_date date not null,
    created_by bigint not null references users,
    status varchar(20) not null,
    created_at timestamptz not null default now(),
    resolved_at timestamptz,
    resolved_by bigint references users,
    constraint chk_task_makeup_links_date_order check (past_date < linked_date)
);

-- Race-safety, same pattern as V19's idx_task_responses_single_active: at most
-- one PENDING link may exist per missed instance, closing the check-then-act
-- race between two employees linking the same missed instance concurrently.
create unique index idx_task_makeup_links_pending
    on task_makeup_links (task_id, store_id, past_date)
    where status = 'PENDING';

-- Fulfillment lookup: all PENDING links for a task/store whose linked_date is
-- "today", read+locked inside the same transaction that completes today's
-- instance (TaskMakeupLinkService.fulfillPendingLinksIfCompleted).
create index idx_task_makeup_links_fulfillment
    on task_makeup_links (task_id, store_id, linked_date, status);

-- Lazy-expiry sweep (before any link read/write) and the nightly job: all
-- PENDING links whose linked_date has passed.
create index idx_task_makeup_links_expiry
    on task_makeup_links (status, linked_date);
