-- Immutable audit trail for Owner/Admin corrections to a past stock check.
-- admin_corrections cannot be reused: its task_response_id FK is NOT NULL
-- and non-polymorphic. See StockCheckCorrection entity.
CREATE TABLE stock_check_corrections (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_check_id        BIGINT       NOT NULL REFERENCES stock_checks(id),
    original_count        INTEGER      NOT NULL,
    corrected_count        INTEGER      NOT NULL,
    corrected_by_user_id   BIGINT       NOT NULL REFERENCES users(id),
    reason                VARCHAR(200),
    corrected_at          TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_stock_check_corrections_stock_check_id ON stock_check_corrections(stock_check_id);
