-- The shared dev database had inventory_items dropped and store_inventory_items
-- denormalized (name/unit_of_measurement/category_id added directly) by a migration
-- that was never committed to this repo. The InventoryItem entity, its repository/
-- service, and StoreInventoryItem.inventoryItem (FK column inventory_item_id) still
-- expect the original normalized shape, so restore it here without touching code.
CREATE TABLE inventory_items (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id             BIGINT        NOT NULL,
    name                    TEXT          NOT NULL,
    unit_of_measurement     TEXT          NOT NULL,
    active                  BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ   NOT NULL,
    updated_at              TIMESTAMPTZ   NOT NULL
);

CREATE INDEX idx_inventory_items_category ON inventory_items(category_id);

ALTER TABLE inventory_items
    ADD CONSTRAINT fk_inventory_items_category FOREIGN KEY (category_id) REFERENCES inventory_categories(id);

-- Reconstruct the catalog from the surviving denormalized rows -- one inventory_item
-- per distinct (category_id, name, unit_of_measurement) combination in use today.
INSERT INTO inventory_items (category_id, name, unit_of_measurement, active, created_at, updated_at)
SELECT category_id, name, unit_of_measurement, true, now(), now()
FROM (
    SELECT DISTINCT category_id, name, unit_of_measurement
    FROM store_inventory_items
) distinct_items;

ALTER TABLE store_inventory_items
    ADD COLUMN inventory_item_id BIGINT;

UPDATE store_inventory_items sii
SET inventory_item_id = ii.id
FROM inventory_items ii
WHERE ii.category_id = sii.category_id
  AND ii.name = sii.name
  AND ii.unit_of_measurement = sii.unit_of_measurement;

ALTER TABLE store_inventory_items
    ALTER COLUMN inventory_item_id SET NOT NULL;

ALTER TABLE store_inventory_items
    ADD CONSTRAINT fk_store_inventory_items_inventory_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id);

CREATE UNIQUE INDEX uq_store_inventory_items_store_item ON store_inventory_items(store_id, inventory_item_id);
