create table tasks (
    id bigint generated by default as identity,
    owner_id bigint not null,
    category_id bigint not null,
    name TEXT not null,
    description TEXT,
    applies_to_all_stores boolean not null default false,
    response_type varchar(20) not null,
    numeric_unit TEXT,
    numeric_min double precision,
    numeric_max double precision,
    text_max_length integer,
    completion_type varchar(20) not null,
    max_completions integer,
    schedule_type varchar(20) not null,
    start_date date not null,
    end_date date,
    time_mode varchar(20) not null default 'ANYTIME',
    start_time time,
    end_time time,
    active boolean not null default true,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    primary key (id)
);
alter table tasks add constraint fk_tasks_owner foreign key (owner_id) references users;
alter table tasks add constraint fk_tasks_category foreign key (category_id) references categories;

create table task_stores (
    task_id bigint not null,
    store_id bigint not null,
    primary key (task_id, store_id)
);
alter table task_stores add constraint fk_task_stores_task foreign key (task_id) references tasks on delete cascade;
alter table task_stores add constraint fk_task_stores_store foreign key (store_id) references stores;

create table task_selected_days (
    task_id bigint not null,
    day varchar(10) not null,
    primary key (task_id, day)
);
alter table task_selected_days add constraint fk_task_selected_days_task foreign key (task_id) references tasks on delete cascade;
