package com.nforce.retailops.service;

import com.nforce.retailops.dto.AdminCorrectionApplyResponse;
import com.nforce.retailops.dto.AdminCorrectionEntry;
import com.nforce.retailops.dto.AdminCorrectionRequest;
import com.nforce.retailops.dto.HistoryResponseEntryResponse;
import com.nforce.retailops.entity.AdminCorrection;
import com.nforce.retailops.entity.ResponseType;
import com.nforce.retailops.entity.TaskResponseEntry;
import com.nforce.retailops.exception.InvalidTaskResponseException;
import com.nforce.retailops.exception.StoreNotFoundException;
import com.nforce.retailops.exception.TaskResponseNotFoundException;
import com.nforce.retailops.exception.UnauthorizedTaskResponseActionException;
import com.nforce.retailops.repository.AdminCorrectionRepository;
import com.nforce.retailops.repository.StoreOwnerRepository;
import com.nforce.retailops.repository.TaskResponseEntryRepository;
import com.nforce.retailops.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
public class AdminCorrectionService {

    private final TaskResponseEntryRepository taskResponseEntryRepository;
    private final AdminCorrectionRepository adminCorrectionRepository;
    private final StoreOwnerRepository storeOwnerRepository;
    private final UserRepository userRepository;
    private final NotificationService notificationService;
    private final ActivityLogService activityLogService;

    public AdminCorrectionService(
        TaskResponseEntryRepository taskResponseEntryRepository,
        AdminCorrectionRepository adminCorrectionRepository,
        StoreOwnerRepository storeOwnerRepository,
        UserRepository userRepository,
        NotificationService notificationService,
        ActivityLogService activityLogService
    ) {
        this.taskResponseEntryRepository = taskResponseEntryRepository;
        this.adminCorrectionRepository = adminCorrectionRepository;
        this.storeOwnerRepository = storeOwnerRepository;
        this.userRepository = userRepository;
        this.notificationService = notificationService;
        this.activityLogService = activityLogService;
    }

    @Transactional
    public AdminCorrectionApplyResponse correctResponse(
        Long responseId, Long adminUserId, String adminDisplayName, AdminCorrectionRequest request
    ) {
        TaskResponseEntry entry = taskResponseEntryRepository.findById(responseId)
            .filter(TaskResponseEntry::isActive)
            .orElseThrow(() -> new TaskResponseNotFoundException("Response not found"));

        // Super Admin (adminUserId == null) can correct any store. Owner/Admin is scoped to their own store.
        if (adminUserId != null) {
            storeOwnerRepository.findByStoreIdAndOwnerId(entry.getStore().getId(), adminUserId)
                .orElseThrow(() -> new UnauthorizedTaskResponseActionException(
                    "You can only correct responses belonging to your own store"));
        }

        // "Missed Tasks" makeup rows auto-generated by fulfilling a link are permanent --
        // see CompletedVia.LINK_FULFILLED and TaskMakeupLinkService.
        if (entry.getCompletedVia() == com.nforce.retailops.entity.CompletedVia.LINK_FULFILLED) {
            throw new com.nforce.retailops.exception.MakeupResponsePermanentException(
                "This response was auto-completed via a linked task and cannot be corrected");
        }

        if (request.reason() == null || request.reason().isBlank()) {
            throw new InvalidTaskResponseException("A reason is required when correcting a response");
        }
        String trimmedReason = request.reason().trim();
        if (trimmedReason.length() > 200) {
            throw new InvalidTaskResponseException("Reason must be 200 characters or fewer");
        }

        AdminCorrection correction = new AdminCorrection();
        correction.setTaskResponse(entry);
        if (adminUserId != null) {
            correction.setCorrectedBy(userRepository.getReferenceById(adminUserId));
        } else {
            correction.setCorrectedByName(adminDisplayName);
        }
        correction.setReason(trimmedReason);

        // Capture original values before overwriting.
        correction.setOriginalValueBoolean(entry.getValueBoolean());
        correction.setOriginalValueNumeric(entry.getValueNumeric());
        correction.setOriginalValueText(entry.getValueText());

        // Validate and apply corrected value, using the same response-type rules as
        // the original submission (applyValue in TaskService).
        switch (entry.getResponseType()) {
            case YES_NO, DONE_NOT_DONE -> {
                if (request.correctedBooleanValue() == null) {
                    throw new InvalidTaskResponseException("A Yes/No response is required");
                }
                correction.setCorrectedValueBoolean(request.correctedBooleanValue());
                entry.setValueBoolean(request.correctedBooleanValue());
                entry.setValueNumeric(null);
                entry.setValueText(null);
            }
            case NUMERIC -> {
                if (request.correctedNumericValue() == null) {
                    throw new InvalidTaskResponseException("A numeric response is required");
                }
                Double min = entry.getTask().getNumericMin();
                Double max = entry.getTask().getNumericMax();
                if (min != null && request.correctedNumericValue() < min) {
                    throw new InvalidTaskResponseException("Value must be at least " + min);
                }
                if (max != null && request.correctedNumericValue() > max) {
                    throw new InvalidTaskResponseException("Value must be at most " + max);
                }
                correction.setCorrectedValueNumeric(request.correctedNumericValue());
                entry.setValueNumeric(request.correctedNumericValue());
                entry.setValueBoolean(null);
                entry.setValueText(null);
            }
            case TEXT -> {
                if (request.correctedTextValue() == null) {
                    throw new InvalidTaskResponseException("A text response is required");
                }
                Integer maxLen = entry.getTask().getTextMaxLength();
                if (maxLen != null && request.correctedTextValue().length() > maxLen) {
                    throw new InvalidTaskResponseException("Text must be " + maxLen + " characters or fewer");
                }
                correction.setCorrectedValueText(request.correctedTextValue());
                entry.setValueText(request.correctedTextValue());
                entry.setValueBoolean(null);
                entry.setValueNumeric(null);
            }
        }

        taskResponseEntryRepository.save(entry);
        AdminCorrection saved = adminCorrectionRepository.save(correction);
        notificationService.createForCorrection(saved);

        String correctorName = adminUserId != null
            ? userRepository.findById(adminUserId).map(u -> u.getFullName()).orElse(adminDisplayName)
            : adminDisplayName;
        activityLogService.log(
            "RESPONSE_CORRECTED", correctorName, adminUserId != null ? "OWNER_ADMIN" : "SUPER_ADMIN",
            entry.getStore().getId(), entry.getStore().getName(), "TASK", entry.getTask().getName(),
            "Corrected a response for \"" + entry.getTask().getName() + "\""
        );

        AdminCorrectionEntry correctionDto = ChecklistHistoryService.toCorrectionEntry(saved);
        HistoryResponseEntryResponse updatedResponse = new HistoryResponseEntryResponse(
            entry.getId(),
            entry.getEmployee().getId(),
            entry.getEmployee().getFullName(),
            null, // empId not critical in correction response; admin already knows the employee
            entry.getValueBoolean(),
            entry.getValueNumeric(),
            entry.getValueText(),
            entry.getCreatedAt(),
            correctionDto,
            entry.getEmployee().getAvatarUrl(),
            entry.isFlaggedNeedsCorrection(),
            entry.getFlagReason(),
            ChecklistHistoryService.buildResubmissionHistory(entry, taskResponseEntryRepository, adminCorrectionRepository),
            false,
            entry.getCompletedVia()
        );

        return new AdminCorrectionApplyResponse(updatedResponse, correctionDto);
    }

    @Transactional
    public HistoryResponseEntryResponse flagResponse(Long responseId, Long adminUserId, String adminDisplayName, String reason) {
        TaskResponseEntry entry = taskResponseEntryRepository.findById(responseId)
            .filter(TaskResponseEntry::isActive)
            .orElseThrow(() -> new TaskResponseNotFoundException("Response not found"));

        if (adminUserId != null) {
            storeOwnerRepository.findByStoreIdAndOwnerId(entry.getStore().getId(), adminUserId)
                .orElseThrow(() -> new UnauthorizedTaskResponseActionException(
                    "You can only flag responses belonging to your own store"));
        }

        if (reason == null || reason.isBlank()) {
            throw new InvalidTaskResponseException("A reason is required when flagging a response");
        }
        String trimmedReason = reason.trim();
        if (trimmedReason.length() > 500) {
            throw new InvalidTaskResponseException("Reason must be 500 characters or fewer");
        }

        // Mark the response as needing correction (stays active so history/admin view still shows it).
        entry.setFlaggedNeedsCorrection(true);
        entry.setFlagReason(trimmedReason);
        taskResponseEntryRepository.save(entry);

        // Audit record — no corrected values since admin didn't edit the value directly.
        AdminCorrection flag = new AdminCorrection();
        flag.setTaskResponse(entry);
        if (adminUserId != null) {
            flag.setCorrectedBy(userRepository.getReferenceById(adminUserId));
        } else {
            flag.setCorrectedByName(adminDisplayName);
        }
        flag.setReason(trimmedReason);
        flag.setCorrectionType("FLAG_TO_EMPLOYEE");
        flag.setOriginalValueBoolean(entry.getValueBoolean());
        flag.setOriginalValueNumeric(entry.getValueNumeric());
        flag.setOriginalValueText(entry.getValueText());
        AdminCorrection saved = adminCorrectionRepository.save(flag);

        notificationService.createForFlag(saved);

        String flaggerName = adminUserId != null
            ? userRepository.findById(adminUserId).map(u -> u.getFullName()).orElse(adminDisplayName)
            : adminDisplayName;
        activityLogService.log(
            "RESPONSE_FLAGGED", flaggerName, adminUserId != null ? "OWNER_ADMIN" : "SUPER_ADMIN",
            entry.getStore().getId(), entry.getStore().getName(), "TASK", entry.getTask().getName(),
            "Flagged a response for \"" + entry.getTask().getName() + "\""
        );

        AdminCorrectionEntry correctionDto = ChecklistHistoryService.toCorrectionEntry(saved);
        return new HistoryResponseEntryResponse(
            entry.getId(),
            entry.getEmployee().getId(),
            entry.getEmployee().getFullName(),
            null,
            entry.getValueBoolean(),
            entry.getValueNumeric(),
            entry.getValueText(),
            entry.getCreatedAt(),
            correctionDto,
            entry.getEmployee().getAvatarUrl(),
            true,
            trimmedReason,
            ChecklistHistoryService.buildResubmissionHistory(entry, taskResponseEntryRepository, adminCorrectionRepository),
            false,
            entry.getCompletedVia()
        );
    }

    @Transactional(readOnly = true)
    public List<AdminCorrectionEntry> getCorrectionHistory(Long responseId, Long adminUserId) {
        TaskResponseEntry entry = taskResponseEntryRepository.findById(responseId)
            .orElseThrow(() -> new TaskResponseNotFoundException("Response not found"));

        if (adminUserId != null) {
            storeOwnerRepository.findByStoreIdAndOwnerId(entry.getStore().getId(), adminUserId)
                .orElseThrow(() -> new UnauthorizedTaskResponseActionException(
                    "You can only view corrections for responses belonging to your own store"));
        }

        return ChecklistHistoryService.buildCorrectionHistory(
            entry, taskResponseEntryRepository, adminCorrectionRepository);
    }
}
